# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('hostname', models.CharField(max_length=30)),
                ('console_ip', models.CharField(max_length=15)),
                ('console_username', models.CharField(max_length=30)),
                ('console_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=30)),
                ('tftp_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
